### PR TITLE
Handle invalid molecules

### PR DESCRIPTION
**Pull request by c-feldmann**
This PR will allow to handle erroneous molecules to be skipped during processing without failing the entire pipeline.

### CODE REVIEW

**Comment by EBjerrum** [comment]
Fantastic, hope to get time to look at it soon!

**Comment by EBjerrum** [comment]
I'll pull into a new branch and look at it further, there seem to be some type incompatibilities flagged in the automatic testing.

**Comment by EBjerrum** [comment]
Do you have more time to work on this, or should I simply take what I can use?

**Comment by c-feldmann** [comment]
> Do you have more time to work on this, or should I simply take what I can use?

Hey, sorry for the late reply. Take what you can use.

**Comment by EBjerrum** [comment]
Thanks, there's some good ideas in there

**Pull request merged**
